# Generated by Django 3.0.1 on 2019-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING ORDER', 'PENDING ORDER'), ('ORDER TREATED', 'ORDER TREATED'), ('ORDER DELIVERED', 'ORDER DELIVERED')], default='PENDING ORDER', max_length=50),
        ),
    ]
